#!/bin/bash

# Sync photos directory to Cloudflare R2
#
# Usage:
#   ./scripts/sync-to-r2          # sync all of photos/
#   ./scripts/sync-to-r2 dev      # sync photos/dev/ to dev/
#   ./scripts/sync-to-r2 2025     # sync photos/2025/ to 2025/

python3 scripts/utils/sync_to_r2.py "$@"
